export const seoPagesData = [
  { slug: "vender-cupo-banco-falabella-cmr", title: "Vender Cupo Banco Falabella CMR", bankName: "Banco Falabella", cardType: "CMR" },
  { slug: "cambiar-cupo-tarjeta-cencosud-scotiabank", title: "Cambiar Cupo Tarjeta Cencosud Scotiabank", bankName: "Cencosud", cardType: "Scotiabank" },
  { slug: "avance-efectivo-tarjeta-ripley", title: "Avance Efectivo Tarjeta Banco Ripley", bankName: "Banco Ripley", cardType: "Mastercard" },
  { slug: "vender-cupo-tarjeta-lider-bci", title: "Vender Cupo Tarjeta Lider Bci", bankName: "Lider Bci", cardType: "Visa" },
  { slug: "cambio-cupo-dolar-abcvisa", title: "Cambio Cupo Dólar Abcvisa", bankName: "Abcvisa", cardType: "Visa" },
  { slug: "vender-cupo-tarjeta-hites", title: "Vender Cupo Tarjeta Hites", bankName: "Hites", cardType: "Transbank" },
  { slug: "avance-efectivo-tarjeta-la-polar", title: "Avance Efectivo Tarjeta La Polar", bankName: "La Polar", cardType: "Visa" },
  { slug: "vender-cupo-tarjeta-cruz-verde", title: "Vender Cupo Tarjeta Cruz Verde", bankName: "Cruz Verde", cardType: "Visa" },
  { slug: "vender-cupo-banco-estado", title: "Vender Cupo Internacional BancoEstado", bankName: "BancoEstado", cardType: "Visa/Mastercard" },
  { slug: "cambiar-cupo-dolar-banco-chile", title: "Cambiar Cupo Dólar Banco de Chile", bankName: "Banco de Chile", cardType: "Visa/Mastercard" },
  { slug: "vender-cupo-banco-santander", title: "Vender Cupo Banco Santander", bankName: "Banco Santander", cardType: "Visa/Mastercard" },
  { slug: "avance-cupo-scotiabank", title: "Avance Cupo Dólar Scotiabank", bankName: "Scotiabank", cardType: "Visa/Mastercard" },
  { slug: "vender-cupo-bci", title: "Vender Cupo Banco Bci", bankName: "Bci", cardType: "Visa/Mastercard" },
  { slug: "cambiar-cupo-itau", title: "Cambiar Cupo Banco Itaú", bankName: "Itaú", cardType: "Visa/Mastercard" },
  { slug: "vender-cupo-banco-security", title: "Vender Cupo Banco Security", bankName: "Banco Security", cardType: "Mastercard Black" },
  { slug: "cambio-cupo-banco-bice", title: "Cambio Cupo Banco Bice", bankName: "Banco Bice", cardType: "Visa Infinite" },
  { slug: "vender-cupo-banco-edwards", title: "Vender Cupo Banco Edwards", bankName: "Banco Edwards", cardType: "Visa/Mastercard" },
  { slug: "avance-efectivo-coopeuch", title: "Avance Efectivo Coopeuch", bankName: "Coopeuch", cardType: "Mastercard" },
  { slug: "vender-cupo-banco-consorcio", title: "Vender Cupo Banco Consorcio", bankName: "Banco Consorcio", cardType: "Visa" },
  { slug: "cambiar-cupo-banco-internacional", title: "Cambiar Cupo Banco Internacional", bankName: "Banco Internacional", cardType: "Mastercard" }
];
